/**
 * fntParser.ts
 *
 * Parses BMFont text format (.fnt files generated by tools like
 * GlyphDesigner, Hiero, BMFont, etc.)
 *
 * Text format example:
 *   info face="Arial" size=32 ...
 *   common lineHeight=38 base=30 scaleW=512 scaleH=512 pages=1 ...
 *   page id=0 file="arial.png"
 *   chars count=95
 *   char id=32 x=506 y=0 width=3 height=1 xoffset=-1 yoffset=29 xadvance=9 ...
 *   kernings count=0
 */

export interface FntChar {
  id: number
  x: number
  y: number
  width: number
  height: number
  xoffset: number
  yoffset: number
  xadvance: number
  page: number
}

export interface FntData {
  face: string
  size: number
  lineHeight: number
  base: number
  scaleW: number
  scaleH: number
  /** Texture page filename */
  pageFile: string
  chars: Map<number, FntChar>
}

export function parseFnt(content: string): FntData {
  const lines = content.split(/\r?\n/)

  let face = ''
  let size = 0
  let lineHeight = 0
  let base = 0
  let scaleW = 0
  let scaleH = 0
  let pageFile = ''
  const chars = new Map<number, FntChar>()

  for (const line of lines) {
    const tag = line.split(' ')[0]

    if (tag === 'info') {
      face = readAttr(line, 'face') || ''
      size = parseInt(readAttr(line, 'size') || '0', 10)
    } else if (tag === 'common') {
      lineHeight = parseInt(readAttr(line, 'lineHeight') || '0', 10)
      base       = parseInt(readAttr(line, 'base')       || '0', 10)
      scaleW     = parseInt(readAttr(line, 'scaleW')     || '0', 10)
      scaleH     = parseInt(readAttr(line, 'scaleH')     || '0', 10)
    } else if (tag === 'page') {
      // file="texture.png"  or file=texture.png
      pageFile = readAttr(line, 'file') || ''
    } else if (tag === 'char') {
      const id = parseInt(readAttr(line, 'id') || '0', 10)
      chars.set(id, {
        id,
        x:        parseInt(readAttr(line, 'x')        || '0', 10),
        y:        parseInt(readAttr(line, 'y')        || '0', 10),
        width:    parseInt(readAttr(line, 'width')    || '0', 10),
        height:   parseInt(readAttr(line, 'height')   || '0', 10),
        xoffset:  parseInt(readAttr(line, 'xoffset')  || '0', 10),
        yoffset:  parseInt(readAttr(line, 'yoffset')  || '0', 10),
        xadvance: parseInt(readAttr(line, 'xadvance') || '0', 10),
        page:     parseInt(readAttr(line, 'page')     || '0', 10),
      })
    }
  }

  return { face, size, lineHeight, base, scaleW, scaleH, pageFile, chars }
}

/** Read a key=value or key="value" attribute from a BMFont text line */
function readAttr(line: string, key: string): string | null {
  // Match: key="value" or key=value (no spaces in value)
  const re = new RegExp(`\\b${key}="([^"]*)"`)
  let m = line.match(re)
  if (m) return m[1]
  const re2 = new RegExp(`\\b${key}=(\\S+)`)
  m = line.match(re2)
  return m ? m[1] : null
}
